const teamLogos = [
    'hawks-logo.png',
    'rockets-logo.png',
    'pacers-logo.png',
    'clippers-logo.png',
    'lakers-logo.png',
    'grizzlies-logo.png',
    'heat-logo.png',
    'bucks-logo.png',
    'timberwolves-logo.png',
    'pelicans-logo.png',
    'knicks-logo.png',
    'thunder-logo.png',
    'magic-logo.png',
    '76ers-logo.png',
    'celtics-logo.png',
    'nets-logo.png',
    'suns-logo.png',
    'bulls-logo.png',
    'hornets-logo.png',
    'trail-blazers-logo.png',
    'kings-logo.png',
    'spurs-logo.png',
    'raptors-logo.png',
    'jazz-logo.png',
    'wizards-logo.png',
    'mavericks-logo.png',
    'cavaliers-logo.png',
    'nuggets-logo.png',
    'warriors-logo.png',
    'pistons-logo.png',
]

export default teamLogos